### ISSUE TITLE
New extension point: sequence 

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#110]
I'm thinking about adding a new `sequence` extension point that serves two purposes:

1. It should make up for Go's lack of support for lookarounds in patterns.
2. It should incorporate POS tags, allowing for more grammar-focused rules.

Here's what I'm thinking so far:

```yml
# Basic case: 
#
# This will warn about using 'his' unless it's followed by 'or her'
# (and vice versa).
extends: sequence
message: "Don't use '%s'"
# How to split the tokens:
split: '  ' 
tokens: 
  - 
    pattern: (?:his|her)
    match: true
    capture: true # Will be passed to `message`
  - 
    pattern: or
    match: false
  - 
    pattern: (?:his|her)
    match: false
```

```yml
# POS case: This will match the word 'this', if it's followed by anything token 
# with POS != 'NN'.
message: "Don't use '%s'"
extends: sequence
# How to split the tokens:
split: '  ' 
tokens: 
  - pattern: him
    match: true

  - pos: NN
    match: false
```
