### ISSUE TITLE
Error with consistency style rule?

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#129]
I have been testing creating a new consistency check, and couldn't get it to work, so thought I'd just try the example rule from the [docs](https://errata-ai.github.io/vale/styles/#consistency).

But that doesn't trigger either. Here's my test markdown file:

```
# Test

The centre issue is that everything is going to the center.
```

Is the example config wrong, or something else? Latest vale, installed with Homebrew, running on a mac. Tried with VSC package and command line.

**Comment by jdkato** [comment]
Using that snippet with the files below and `v1.4.1`, I get:

```console
 test.md
 3:53  error  Inconsistent spelling of        Test.Spelling 
              'center'                                      

✖ 1 error, 0 warnings and 0 suggestions in 1 file.                              
```

Can you reproduce this?

---

```ini
# .vale.ini
StylesPath = styles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = Test
```

```yaml
# styles/Test/Spelling.yml
extends: consistency
message: "Inconsistent spelling of '%s'"
level: error
scope: text
ignorecase: true
nonword: false
# We only want one of these to appear.
either:
  advisor: adviser
  centre: center
```
