### ISSUE TITLE
Scope to specific heading levels in Markdown

### ISSUE THREAD

**Issue by eojthebrave** [vale-cli/vale#143]
I would like to use Value to check the case of title's in a Markdown document. In my case all `h1` headings should be title case, while all those `h2` and below should be sentence case. But, I can't figure out how to write a rule that will target for example just the `h1` headings.'

My current rule looks like this:

```yaml
extends: capitalization
message: "'%s' should be in title case"
level: warning
scope: heading
# $title, $sentence, $lower, $upper, or a pattern.
match: $title
```

Is it possible do something like `scope: heading.h1`. Or to write this rule in some other way that would make it target just h1, or just h2 headings?

**Comment by jdkato** [comment]
Yes, this should work:

```yaml
extends: capitalization
message: "'%s' should be in title case"
level: warning
# Could be `heading.h2`, `heading.h3`, etc.
scope: heading.h1
match: $title
```
