### ISSUE TITLE
Style exceptions not behaving as expected

### ISSUE THREAD

**Issue by StarfallProjects** [vale-cli/vale#154]
- OS: Windows 10
- Install method: chocolatey
- Vale version: 1.7.1

Hi! We're seeing some unexpected results with title case rules and exceptions.

Our setup is:
```
StylesPath = styles
MinAlertLevel = warning
[*.{md}]
BasedOnStyles = EventStore, 18F, write-good
18F.Titles = No
```
Then in `styles/EventStore/Titles.yml`
```
---
extends: capitalization
message: "'%s' should be in sentence case"
level: warning
scope: heading
match: $sentence
exceptions:
  - Event Store
```

Vale then does the following:

`## Event Store` -> ok
`## Creating a connection to Event Store` -> warning

There is a further quirk. If I modify the exceptions as follows:

```
exceptions:
  - Event Store
  - Creating a connection to Event Store
```

It gives the same results:

`## Event Store` -> ok
`## Creating a connection to Event Store` -> warning

What should the behaviour be?

**Comment by jdkato** [comment]
`Event` and `Store` should be added as individual exceptions:

```yaml
---
extends: capitalization
message: "'%s' should be in sentence case"
level: warning
scope: heading
match: $sentence
exceptions:
  - Event 
  - Store
```
This should allow both `## Event Store` and `## Creating a connection to Event Store` to pass. I'll make this more clear in the documentation.
