### ISSUE TITLE
Ignore comments are not honored in a markdown or reStructuredText file inside a list

### ISSUE THREAD

**Issue by gaurav-nelson** [vale-cli/vale#175]
I probably have an edge case. I have put in `<!-- vale off -->` comment (inside a numbered list) in my markdown file but its still reporting errors. 

I have a numbered list with a YAML code example (test1.md) and have put it ignore comments for second list item. However, Vale is not honoring the ignore comments. 
But it works fine (show no errors) if I remove `---` from my YAML example (test2.md).

I have added test1.md and test2.md below, and I am using Microsoft style.

#### Vale error
````
test.md

 44:8   error       Use "shouldn't" instead of      Microsoft.Contractions
                    "should not".
 44:29  suggestion  'be used' looks like passive    Microsoft.Passive
                    voice.
 45:4   suggestion  Verify your use of 'Ensure'     Microsoft.Vocab
                    with the A-Z word list.
 45:33  error       Use "aren't" instead of "are    Microsoft.Contractions
                    not".

✖ 2 errors, 0 warnings and 2 suggestions in 1 file.
````

<details><summary> test1.md</summary>
<p>

`````
1. Consider the following `deployment.yaml` file.
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: my-nginx-svc
     labels:
       app: nginx
   spec:
     type: LoadBalancer
     ports:
     - port: 80
     selector:
       app: nginx
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: my-nginx
     labels:
       app: nginx
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: nginx
     template:
       metadata:
         labels:
           app: nginx
       spec:
         containers:
         - name: nginx
           image: nginx:1.7.9
           ports:
           - containerPort: 80
   ```

1. few other steps.
<!-- vale off -->
1. The output lists the failure code and policy violation details.
   ```bash
   SSH should not typically be used within containers.
   Ensure that non-SSH services are not using port 22.
   ```
<!-- vale on -->

something else.
`````

</p>
</details>

<details><summary> test2.md</summary>
<p>

`````

1. Consider the following `deployment.yaml` file.
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: my-nginx-svc
     labels:
       app: nginx
   spec:
     type: LoadBalancer
     ports:
     - port: 80
     selector:
       app: nginx
   
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: my-nginx
     labels:
       app: nginx
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: nginx
     template:
       metadata:
         labels:
           app: nginx
       spec:
         containers:
         - name: nginx
           image: nginx:1.7.9
           ports:
           - containerPort: 80
   ```

1. few other steps.
<!-- vale off -->
1. The output lists the failure code and policy violation details.
   ```bash
   SSH should not typically be used within containers.
   Ensure that non-SSH services are not using port 22.
   ```
<!-- vale on -->

something else.

`````

</p>
</details>

--------

- OS: Linux
- Install method: direct download 
- Vale version: 2.0.0

**Comment by jdkato** [comment]
Thanks for the report.

Are you able to share the actual Markdown file (or a functionally equivalent copy of) containing the `<!-- vale off -->` comments? It's not clear to me where exactly these comments are from your rendered examples.

**Comment by gaurav-nelson** [comment]
Thanks @jdkato 

Here are the contents of:

1.  `test1.md` file

`````

1. Consider the following `deployment.yaml` file.
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: my-nginx-svc
     labels:
       app: nginx
   spec:
     type: LoadBalancer
     ports:
     - port: 80
     selector:
       app: nginx
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: my-nginx
     labels:
       app: nginx
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: nginx
     template:
       metadata:
         labels:
           app: nginx
       spec:
         containers:
         - name: nginx
           image: nginx:1.7.9
           ports:
           - containerPort: 80
   ```

1. few other steps.
<!-- vale off -->
1. The output lists the failure code and policy violation details.
   ```bash
   SSH should not typically be used within containers.
   Ensure that non-SSH services are not using port 22.
   ```
<!-- vale on -->

something else.

`````

2. `test2.md` file. (Same as `test1.md` without `---` appearing in yaml example.
`````
1. Consider the following `deployment.yaml` file.
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: my-nginx-svc
     labels:
       app: nginx
   spec:
     type: LoadBalancer
     ports:
     - port: 80
     selector:
       app: nginx
   
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: my-nginx
     labels:
       app: nginx
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: nginx
     template:
       metadata:
         labels:
           app: nginx
       spec:
         containers:
         - name: nginx
           image: nginx:1.7.9
           ports:
           - containerPort: 80
   ```

1. few other steps.
<!-- vale off -->
1. The output lists the failure code and policy violation details.
   ```bash
   SSH should not typically be used within containers.
   Ensure that non-SSH services are not using port 22.
   ```
<!-- vale on -->

something else.
`````
