### ISSUE TITLE
Extend base config

### ISSUE THREAD

**Issue by acalvo** [vale-cli/vale#176]
There is no way to extend a base config, is there?

I mean, I'd like to have a base `.vale.ini` config file somewhere, and then in each project's `.vale.ini` do something like:

```yaml
Extend = path/to/base/.vale.ini
# and here override some config
```

**Comment by ChrisChinchilla** [comment]
Not that I know of, but a few of us are trying to develop some kind of "recommended way" to do this. Nearly there with it ;)

**Comment by glerchundi** [comment]
Which is the status of this one? Thanks!

**Comment by ChrisChinchilla** [comment]
This will be something that takes a while from a functionality perspective, from a "best practices" perspective, I need to find the time to write this up, and as a full time freelance writer, that also takes some time… But I also found a better way to accomplish what I have been doing so far. So keep watching this space.

**Comment by glerchundi** [comment]
Thanks for the update!

**Comment by NicolasMassart** [comment]
I use `cat` to do this in my CI scripts, here are the two relevant CircleCI steps:

```
      - run:
          name: Cat config
          command: |
            cat .circleci/additional-vale.ini >> ./common/build_tools/vale/.vale.ini
      - run:
          name: Run Vale
          command: |
            ./bin/vale --config ./common/build_tools/vale/.vale.ini --glob='*.{md}' . | tee ./vale.out
```
- `.circleci/additional-vale.ini` is the project specific one
- `./common/build_tools/vale/.vale.ini` is the common one (`/common` is a Git submodule in each project)

Works with Vale 2.4.0.

Of course with this you can only add rules and not override some settings already in the common config.
