### ISSUE TITLE
Feature request: Extension point for custom messages

### ISSUE THREAD

**Issue by gaurav-nelson** [vale-cli/vale#181]
All existing extension points, shows the same message for all matches. 

For example, consider the following excerpt from `Microsoft/Vocab.yml`:
```yml
extends: existence
message: "Verify your use of '%s' with the A-Z word list."
link: 'https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/abort-abortion'
level: suggestion
ignorecase: true
tokens:
  - above
  - accessible
  - actionable
  - against
```

For all matches it points users to verify word usage from a specific web address.

If we can have a custom message extension, that could show specific messages for specific terms, it would save us from referring users to a web address and specific usage instruction right there in vale.

So maybe something like:
```yml
extends: existence
link: 'https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/'
level: suggestion
ignorecase: true
custommessage:
  - above: Don't use to mean earlier.
  - accessible: Reserve accessible and accessibility to refer to things that are easy to use for everyone, including people with disabilities.
  - actionable: Don't use unless you have no other choice.
  - against: Don't use to refer to running or building a program on a particular platform or operating system. Use on instead.
```

Similar to `swap`, maybe `custommessage` (or whatever you wanna call that) it could take in two things or more:
```
- <word>: <usage advice>| <specific-URL>
```
For example:
```
  - above: Don't use %s to mean earlier. | https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/above
```

```
src/content/file.md
 47:1  suggestion  Don't use 'above' to mean earlier.      Microsoft.Vocab
```

I am not sure if this one was requested earlier.

**Comment by jdkato** [comment]
I've looked into this and I think it would be too drastic of a syntax change for `existence`. You can can very similar behavior with `substitution`, though:

```yml
extends: substitution
level: warning
message: "%s"
swap:
  platform: "Avoid using 'platform', unless it actually is one"
  portal: "Avoid using 'portal', unless to another dimension"
```
