### ISSUE TITLE
False positive for links with empty caption

### ISSUE THREAD

**Issue by alcazaco** [vale-cli/vale#184]
Hi!
I use vale version v2.1.0 on Windows.

I have the following rule that makes users stop writing like `See [this topic](//url).`

The rule looks like follows.

```yml
extends: existence
message: "Do not name links like '%s'. Better paste topic name here."
level: warning
ignorecase: true
scope: link
tokens:
  - this 
  - link
  - here
  - this topic
  - this document
  - article
  - topic
```

At the same time, we can create links with an empty caption that is automatically substituted with a topic name.

```markdown
The [](xref:401276) topic describes how to deploy your .NET Core 3 WPF application.
```
With the new Vale version (v2.1.0), I get false positive error messages:

![image](https://user-images.githubusercontent.com/20209898/77535087-058fe200-6eab-11ea-9846-c9d70704aece.png)

Looks like Vale considers the text that follows the empty-caption-link as a link scope.

I cannot reproduce this issue with v1.7.1.

Thank you!
Lex
