### ISSUE TITLE
Vale configuration in GitHub Actions for asciidoctor files

### ISSUE THREAD

**Issue by hepabolu** [vale-cli/vale#195]
I am trying to get the Vale GitHub Action working for my book that consists of multiple Asciidoctor files.

So far I have the action working, but I am not sure the official action includes asciidoctor, because it throws error messages on lines in source code blocks.

I would also like for it to use an en_GB dictionary.

These are the configuration files I've used.
.vale.ini
```
StylesPath = .github/styles
MinAlertLevel = suggestion

[./*.md]
BasedOnStyles = Vale

[book/*.adoc]
BasedOnStyles = Vale

```

.github/vale-linter.yml
```
name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Vale
        uses: errata-ai/vale-action@v1.0.4
        with:
          styles: |
            Vale
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            https://github.com/errata-ai/proselint/releases/latest/download/proselint.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

```

How can I tell it to ignore the source code blocks and use an en_GB dictionary?
