### ISSUE TITLE
force CI to have an exit code if any of error, warning or suggestion are not 0

### ISSUE THREAD

**Issue by paddyroddy** [vale-cli/vale#218]
In my `.vale.ini` I have `MinAlertLevel = suggestion` which is great for running it locally. However, when running it on travis-ci, I actually want my code to fail if `vale` returns anything. I misunderstood the `MinAlertLevel` flag and thought it would exit without `0` if `suggestion` etc was found.

My `.travis.yml` looks like
```
jobs:
  include:
    - name: vale
      install:
        - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s latest
      script:
        - ./bin/vale .
```

Is there a way of doing it other than manually checking that the output is `0 errors, 0 warnings and 0 suggestions in X files.`?

I was hoping that this would fail the CI.
![image](https://user-images.githubusercontent.com/15052188/86494473-2e0e5e80-bd6d-11ea-81f9-b3cf2214b383.png)

**Comment by jdkato** [comment]
No, there's currently no way to return a non-zero code on sub-error alerts.

You *can* change a rule's severity in your config file with `Style.Rule = error`.

**Comment by paddyroddy** [comment]
ah okay, I'm using a fair few rules so didn't really want to turn each one to `error`.

I thought about checking if the output starts with `\u2716` or `\u2714` but realise this only depends on `error` or `warning` not `suggestion`

**Comment by paddyroddy** [comment]
for anyone who finds this issue, I've modified my travis to both show all output and get an error code if anything but 0 errors, 0 warnings and 0 suggestions

```
jobs:
  include:
    - name: vale
      install:
        - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s latest
      script:
        - ./bin/vale . | tee /dev/stderr | grep -q "0 errors, 0 warnings and 0 suggestions"
```
