### ISSUE TITLE
`sequence` not working as expected when trying to check extraneous `'s`

### ISSUE THREAD

**Issue by wouter-veeken** [vale-cli/vale#226]
# System
- OS: MacOS Catalina 10.15.5
- Install method: Homebrew for CLI + Atom Package Manager for plugin
- Vale version: 2.3.1

# Description

The new `sequence` extension doesn't work as expected for me. I want to create a rule to catch misuse of `'s` to denote plurality, e.g.:

```
The endpoint's are available.    # Bad!

The API's endpoints are available.    # Okay!

The endpoint's unavailable today.    # Okay!
```

I started from this example:

```
extends: sequence
message: Did you mean "%[1]ss" instead of "%[1]s's"?
tokens:
  - tag: NN
  - pattern: "'s"
  - pattern: "are"
action:
  name: edit
  params:
    - replace
    - "'"
    - ""
```
(See also [WTD Slack thread](https://writethedocs.slack.com/archives/CBWQQ5E57/p1597257353019400?thread_ts=1597226397.006700&cid=CBWQQ5E57).)

This version of the rule never triggered for me, even with a very basic test pattern, potentially due to how my specific environment handles quotes in the `message` string:
```
message: Did you mean "%[1]ss" instead of "%[1]s's"?    # Never triggers
message: "Did you mean %[1]ss instead of %[1]s's?"    # At least triggers with basic test pattern
```
This may be an unrelated issue but I'm pointing it out for completeness' sake.

After fixing the `message`, I still couldn't get the pattern to work. I experimented with a lot of different test patterns:

```
1.
tokens:
  - tag: NN
  - pattern: "test1"
  - pattern: "test2"

# Successfully triggers on "endpoints test1 test2"

2.
tokens: 
  - tag: NN
  - pattern: "test1"
  - pattern: "are"

# Successfully triggers on "endpoints test1 are"

3.
tokens:
  - tag: NN
  - pattern: "'s"
  - pattern: "test2"

# Doesn't trigger on "endpoint's test2" or "endpoint 's test2"

4.
tokens:
  - pattern: "endpoint"
  - pattern: "'s"
  - pattern: "are"

# Doesn't trigger on "endpoint's are" or "endpoint 's are"

5.
tokens:
  - tag: NN
  - pattern: "a"
  - pattern: "are"

# Doesn't trigger on "endpoints a are" (!)

6.
tokens:
  - tag: NN
  - pattern: "1"
  - pattern: are"

# Successfully triggers on "endpoints 1 are"
```
This isn't everything I tried but I hope it paints a pretty detailed picture. The most remarkable part to me is that a single-letter pattern doesn't work, but a single-number pattern does. I also tried a single `'` to no effect. 

Any suggestions? Let me know if more info is needed. Also can do a quick video call if it helps.

**Comment by jdkato** [comment]
`Did you mean "%[1]ss" instead of "%[1]s's"?` should be a valid message format (indeed, it runs as part of the [test suite here](https://github.com/errata-ai/vale/blob/master/styles/LanguageTool/APOS_ARE.yml)), so I don't yet understand why you had an issue with that.

---

When it comes to testing NLP-based rules (in contrast to regex-based), using contrived sentence fragments is to going to be a poor way to judge whether or not they're working. The tagging process is sensitive to almost every aspect of sentence structure (length, word choice / placement, capitalization, punctuation, etc.) and is trained on "real-world" text, so something like `endpoints a are` could yield unexpected results *without* indicating that there's a fixable "problem" (outside of training a new model).

As part of the v2.3.0 release, Vale includes a command, `tag`, that is designed to make developing and understanding these rules easier:

```console
$ vale tag "The endpoint's are available."
The/DT endpoint/NN 's/POS are/VBP available/JJ ./.
``` 
You can see here that the required sequence is in place: `endpoint/NN 's/POS are/VBP`.

```console
$ vale tag "endpoints a are"
endpoints/NNS a/DT are/VBP
```

In contrast, we *don't* have the sequence here.

So, my best suggestion is test the rule on more "realistic," fully-formed sentences like `The endpoint's are available.` and then use the `tag` command to see how they're being tagged. If there are consistent inaccuracies, I'll look into supporting custom models. 

(FWIW, the [underlying implementation is about 96% accurate](https://github.com/jdkato/prose#tagging) on NLTK's subset of the [Penn Treebank corpus](https://catalog.ldc.upenn.edu/docs/LDC95T7/cl93.html).)

**Comment by wouter-veeken** [comment]
**EDIT: Found the cause. Totally neglected to mention that I'm linting an .adoc file, not .md. It works as advertised in .md, but the rule never triggers in .adoc.**

Thanks for the thorough response @jdkato. I think I didn't make myself fully clear: the rule doesn't trigger for me on the provided example sentence (`The endpoint's are available.`). That's why I started testing all these other patterns in the first place.

So, to be totally clear this time, when I use this configuration:

```
extends: sequence
message: Did you mean "%[1]ss" instead of "%[1]s's"?
tokens:
  - tag: NN
  - pattern: "'s"
  - pattern: "are"
action:
  name: edit
  params:
    - replace
    - "'"
    - ""
```

And my document contains this sentence:

```
The endpoint's are available.
```

The rule doesn't trigger for me as it does for you in the screenshot you shared on Slack:
![image](https://user-images.githubusercontent.com/24491811/90234841-9d717680-de20-11ea-92a0-5bc56a37c69c.png)

**EDIT: Again, it works in Markdown, but not ASCIIdoc. Anything you can do? Or is this an ASCIIdoctor issue?**
