### ISSUE TITLE
add a `capitalization` check

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#23]
I'm thinking this will serve two purposes:

1. When we're looking for specific spelling of a word (e.g., JavaScript), we'll simply pass the desired string:

    ```yaml
    extends: capitalization
    tokens:
    # flags any X such that X.lower() == javascript && X != JavaScript
    - JavaScript
    ```

2. It will support variables representing generic cases  (`$lower`, `$upper`, `$title`, etc.) so that we could, for example, check that all headings are in title case.
