### ISSUE TITLE
Parts of speech: Oddities and explorations

### ISSUE THREAD

**Issue by nostodnayr** [vale-cli/vale#266]
I’ve been spending time trying to use part of speech tagging in some rules. Generally, it’s gone quite well.

I ran into a couple of problems today. Notably, I ran vale multiple times and got different results for a rule that uses `pos` each time. Sometimes the rule generated an alert, other times it wouldn’t. I haven’t tracked that precise bug down yet. I’m mentioning it here in case it rings a bell for you.

I’ve started trying to build a rule bit by bit that *works*, trying to discover my own failings in understanding and perhaps also to find a bug.

I’m not quite there yet, but I’ve got something to chew on. See this rule:

```yaml
level      : warning
message    : "%s"
link       : https://support.1password.com/style-guide/#all--all-of

extends: substitution
ignorecase: true

pos: 'all/DT [^ ]+/PRP'

swap:
  'all \w+': Use "all of", not "all".
```

I used Vale 2.5.0 to tag a minimal sentence:

```
$ ./vale25 tag "It includes all them."
It/PRP includes/VBZ all/DT them/PRP ./.
```

Yet when I lint the sentence:

```
$ echo "It includes all them." | ./vale25
✔ 0 errors, 0 warnings and 0 suggestions in stdin.
```

Everything seems to be working with other rules:

```
$ echo "Open the 1Browser." | ./vale25

 stdin.md
 1:10  error  Use "1Password browser"         1Password.words-do_not_use
              instead of "1Browser".

✖ 1 error, 0 warnings and 0 suggestions in stdin.
```

Is this Vale, or is it me…? 😅
