### ISSUE TITLE
Invalid match when using bare links in a list in AsciiDoc

### ISSUE THREAD

**Issue by ggrossetie** [vale-cli/vale#298]
- OS: Linux 
- Install method: Direct download
- Vale version: `vale version 2.6.8`

`.vale.ini`

```ini
StylesPath = docs/.vale
MinAlertLevel = suggestion

[*.adoc]
BasedOnStyles = test
```

`docs/.vale/test/Substitutions.yml`

```yml
extends: substitution
message: Consider using '%s' instead of '%s'
level: error
ignorecase: true
nonword: false
scope: text
swap:
  asciidoctor: Asciidoctor
```

`docs/test.adoc`

```adoc
= Document Title

* https://github.com/asciidoctor/asciidoctor
* http://pryrepl.org/
* http://discuss.asciidoctor.org/page.html
```

#### Current result

```console
$ vale docs/test.adoc

 docs/test.adoc
 5:18  error  Consider using 'Asciidoctor'    test.Substitutions 
              instead of 'asciidoctor'                           

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

#### Expected result

Most of the time, Vale ignores URLs but in this particular case it finds a violation.
If I remove one item in the list then it's working... :thinking:
