### ISSUE TITLE
By default, Vale should ignore AsciiDoc attribute references

### ISSUE THREAD

**Issue by ggrossetie** [vale-cli/vale#300]
- OS: Linux 
- Install method: Direct download
- Vale version: `vale version 2.6.8`

`.vale.ini`

```ini
StylesPath = docs/.vale
MinAlertLevel = suggestion

[*.adoc]
BasedOnStyles = test
```

`docs/.vale/test/Substitutions.yml`

```yml
extends: substitution
message: Consider using '%s' instead of '%s'
level: error
ignorecase: true
nonword: false
scope: text
swap:
  asciidoctor: Asciidoctor
```

`docs/test.adoc`

```adoc
= Document Title

Asciidoctor is great!
Read the {asciidoctor-project-name} documentation.

Unlike AsciiDoc, Asciidoctor is spelled with a lowercase "d".
Please do not use this incorrect capitalization: AsciiDoctor.
```

#### Current result

```console
$ vale docs/test.adoc                            

 docs/test.adoc
 4:11  error  Consider using 'Asciidoctor'    test.Substitutions 
              instead of 'asciidoctor'                           
 7:50  error  Consider using 'Asciidoctor'    test.Substitutions 
              instead of 'AsciiDoctor'                           

✖ 2 errors, 0 warnings and 0 suggestions in 1 file.
```

#### Expected result

Attribute references should be ignored.
