### ISSUE TITLE
scope: code not working

### ISSUE THREAD

**Issue by plaindocs** [vale-cli/vale#321]
Hey folks,

I'm looking at linting *within* codeblocks, but the following is turning up code that isn't in code blocks as well. 

```yml
extends: existence
message: You need to escape emoji colons in codeblocks
level: error
nonword: True
scope: code
tokens:
    - ':[a-z]*:'
 ```

Am I missing something on the selection side? Because codeblocks are ignored by default? But `scope: code` isn't much use if you have to explicitly include the code elsewhere as well.

**Comment by jdkato** [comment]
I'm not sure that I completely understand the issue here, but `scope: code` matches the HTML `<code>` element which includes both *code blocks* and *code spans* in most markup formats.

For example, in your post above, `scope: code` would match both

```yaml
extends: existence
message: You need to escape emoji colons in codeblocks
level: error
nonword: True
scope: code
tokens:
    - ':[a-z]*:'
```
(a code block) and

```
scope: code
```
(a code span).

**Comment by plaindocs** [comment]
That is how I understand the code scope to work.

My source is a mix of Ruby templating and Markdown (inc html). 

```
[formats]
erb = md

[*.md]

TokenIgnores = (<%.*%>), (:[a-z]*:), ({:toc})

BasedOnStyles = Buildkite
```

and I'm getting matches in straight Markdown like this:

```
Once your Build Pipelines are set up, you can update step labels to something more fun than plain text :smiley: (see our [extensive list of supported emojis](https://github.com/buildkite/emojis))
```

Could the token ignore for similar syntax be causing an issue?

**Comment by jdkato** [comment]
Yes, ignored tokens are converted to code spans under the hood (which results in the match for `scope: code`).

In this case, you can get around this by using `scope: raw` and targeting the markup itself:

```yaml
extends: existence
message: You need to escape emoji colons in codeblocks
level: error
nonword: True
scope: raw
tokens:
  - '`:[a-z]*:`'
```
