### ISSUE TITLE
Regex capture groups behave differently between vocab and rules

### ISSUE THREAD

**Issue by NicolasMassart** [vale-cli/vale#341]
I tried to make regex use consistent between my vocab `accept.txt` file and a custom substitution rule I wrote to warn about the use of some words.
I noticed that capture groups are not working the same way in these two contexts.

## Example

In `accept.txt` I can have `cryptocurrenc(y|ies)` with a capture group or better `cryptocurrenc(?:y|ies)` with a non capturing group.

But in `substitution` extending rule, I can only use the non capturing syntax or otherwise it doesn't take the swap into account:

```yaml
extends: substitution
message: Consider using %s instead of "%s"
ignorecase: true
level: error
swap:
  'cryptocurrenc(?:y|ies)': crypto #works
  'cryptocurrenc(y|ies)': crypto #doesn't work
```

## Vale infos

OS: Linux
Vale 2.10.2 installed from `https://install.goreleaser.com/github.com/ValeLint/vale.sh`
