### ISSUE TITLE
Finding single quotes in regex

### ISSUE THREAD

**Issue by olbrichj** [vale-cli/vale#354]
I'm trying to find single quotation marks in combination with Abbriviations e.g. `ABC's `  
For this I'm using the following rule:

```
extends: existence
message: "<long text>"
level: error
tokens:
  - '\b(?:[A-Z]{2,}\'s)'
```

But I always receive a parsing error: `Invalid value provided`

Things I've tried:
```
- "\b(?:[A-Z]{2,}'s)" -> doesn't detect anything
- '\b(?:[A-Z]{2,}\\'s)' -> same parsing error
- '\b(?:[A-Z]{2,}[[:graph:]]s)' -> doesn't detect anything
```

Am I missing something? Or is it currently impossible to search for a single quote within a regex?

**Comment by jdkato** [comment]
[In YAML](https://yaml.org/spec/1.2/spec.html#id2788097), you need to escape nested single-quotes by repeating the character:

```yml
extends: existence
message: "<long text>"
level: error
tokens:
  - '\b(?:[A-Z]{2,}''s)'
```
