### ISSUE TITLE
Can't get regex to check spacing after a paren to work

### ISSUE THREAD

**Issue by mattcone** [vale-cli/vale#357]
Hey there, thanks in advance for fielding a quick question. I believe I've created a regex to check for lack of spacing after a paren (e.g., `[my link](example.com)another phrase`) but I can't get this to fire when it involves Markdown links. Other instances that don't involve Markdown links work fine, but I'd like to find a way to make it work when it involves Markdown links too. Any tips or tricks?

RegEx and example text: https://regex101.com/r/TQoU0p/1

Trying with this:

```yaml
extends: existence
message: '"%s" must contain one and only one space.'
level: error
nonword: true
tokens:
  - '[\S][)][a-zA-Z0-9]'
```

Really appreciate your work on Vale! Thanks for creating this great tool.

**Comment by jdkato** [comment]
If you want to match against markup syntax (which is excluded from the default `scope: text`), you need to use [`scope: raw`](https://docs.errata.ai/vale/scoping#markup):

```yml
extends: existence
message: '"%s" must contain one and only one space.'
level: error
nonword: true
scope: raw
tokens:
  - '[\S][)][a-zA-Z0-9]'
 ```
