### ISSUE TITLE
Improve styling of multiple options

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#37]
For example,

```yaml
message: Use "%s" instead of "%s"
swap:
  foo: bar or baz #  currently the only way to list multiple options
```
results in `Use "bar or baz" instead of "foo"`. I think it would be better as something like:

```yaml
foo: [bar, baz] # => Use "bar" or "baz" instead of "foo"
```
