### ISSUE TITLE
Vale seems to have somewhat irregular behavior on AsciiDoc

### ISSUE THREAD

**Issue by alexpdp7** [vale-cli/vale#376]
Given the following `~/.vale.ini`:

```
StylesPath = .vale-styles

[*.adoc]
BasedOnStyles = FooBarBranding
```

and the following rule  at `~/.vale-styles/FooBarBranding/FooBar.yml`:

```
extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://style.google.com/style/word-list'
level: error
ignorecase: false
action:
  name: replace
swap:
  Foobar: FooBar
  foobar: FooBar
```

I get the following behavior. On this file, links are not properly skipped...

```
$ cat foo.adoc 
At https://cloud.example.com/.

Ansible collection from https://cloud.example.com/foobar.

Install the `foo.bar` Thing collection from.
It requires that python3-foobar modules are installed.
$ vale foo.adoc 

 foo.adoc
 3:51  error  Use 'FooBar' instead of         FooBarBranding.FooBar 
              'foobar'.                                             

✖ 1 error, 0 warnings and 0 suggestions in 1 file.
```

But if I remove the last line from that file (!), it seems they are...

```
$ cat bar.adoc
At https://cloud.example.com/.

Ansible collection from https://cloud.example.com/foobar.

Install the `foo.bar` Thing collection from.
$ vale bar.adoc
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
```
