### ISSUE TITLE
Allow rules to target code spans

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#44]
While most of the time we'll probably want to ignore code spans, there are cases (see #43 and [Rust's style guide](https://github.com/rust-lang/book/blob/master/second-edition/style-guide.md#prose)) where it'd be nice to have access to them without having to use `--ignore-syntax` (which negates the other benefits of Vale's syntax handling&mdash;notably scoping and avoiding things like URLs).

So, I'm thinking of making this optional on a per-rule basis. For example, if we want to enforce omitting parentheses in code spans (as in the Rust style guide), we could write the following:

```yaml
extends: existence
message: "Remove parentheses from '%s'"
description: "When talking about a method in prose, DO NOT include the parentheses."
level: error
nonword: true
code: true # this tells Vale to keep code spans
tokens:
  - '`\w+\(\)`' # something like `read_line()` would be flagged.
```
This is currently being explored on the [`feat/ignore`](https://github.com/ValeLint/vale/tree/feat/ignore) branch.
