### ISSUE TITLE
Readability statistics 

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#47]
I'm thinking about including a new `readability` extension point that will allow users to set standards for metrics like Flesch-Kincaid, Gunning-Fog, and Coleman-Liau. For example,

```yaml
extends: readability
level: warning
metric: Flesch-Kincaid
grade: 8
scope: paragraph
```
This would warn about any paragraphs that exceed a reading level of 8th grade.

The [`prose`](https://github.com/jdkato/prose#summarizing-godoc) library already supports these metrics, so it's just a matter of deciding on the check implementation details.
