### ISSUE TITLE
How to Extend Existence to Error Out on Contractions

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#601]
Here's my yaml config: 
```yaml
extends: existence
message: "Avoid using contractions."
level: error
match:
  - '\b(\w+\'\w+)\b'
ignore_case: true
```

I have other yaml files in this custom folder and they are picked up by `.vale.ini`. I feel like the issue might be in `'\b(\w+\'\w+)\b'` but can't for the heck of my life figure out where the problem is. 

Any help appreciated!
