### ISSUE TITLE
negate attribute in sequence not working as expected

### ISSUE THREAD

**Issue by sophialloyd** [vale-cli/vale#604]
- OS: macOS 
- Install method: Homebrew
- Vale version: 2.23.0

I'm attempting to implement a sequence-based rule but I'm finding that the `negate` attribute is not working as expected. Here is a minimal example for repro

```
extends: sequence
message: "Use a noun phrase after 'that' as a pronoun so that is is clear what you are referring to."
level: suggestion
tokens:
- pattern: '[Tt]hat'
  tag: DT
- tag: NN
  negate: true
```

Switching `negate` between `true` and `false` produces the same result. In both cases they flag these sentences.
```
You can't use that computer because it doesn't work.
You can open that gift when it's your birthday.
```

My intent is that when `negate: true`, the rule flags these sentences
```
You can't use that because it doesn't work.
You can open that when it's your birthday.
```
