### ISSUE TITLE
Capitalization > sentence: unexpected behaviour

### ISSUE THREAD

**Issue by shea4s** [vale-cli/vale#611]
Hello,

We're running version 2.24.x

I have a rule with

```
extends: capitalization
match: $sentence
```

The rule flags mid-sentence capitalised words only if they exceed a percentage of the sentence. For example, if four out of fourteen words are capitalised, I don't get an error. If five out of thirteen words are capitalised, I do get an error.

The purpose of the rule is to find where people have thought a normal noun was a proper noun, so it's exactly the case of "one capitalised word in an entire sentence" that I was hoping the rule would catch.

Is there a way to change the rule so that it does what we need?

Thank you

**Comment by jdkato** [comment]
In the next release, you'll be able to set the threshold to a custom value.

**Comment by shea4s** [comment]
That's brilliant, thank you so much!

**Comment by jdkato** [comment]
Out in `v2.24.4`. Here's an example:

```yaml
extends: capitalization
message: "'%s' should be in title case"
level: error
scope: heading
match: $sentence
# always trigger an alert.
threshold: 1.0
exceptions:
  - ABC
```
