### ISSUE TITLE
How to use RegEx to merge singular and plural swapping suggestions into one

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#632]
I have a custom rule similar to the following:
```
extends: substitution
message: "Use '%s' instead of '%s'."
level: error
swap:
  enduser: end user
  endusers: end users
```

Is there any way I can merge the two swapping suggestions into one? i have tried `'end user?s': end user(s)` but it the `(s)` on the right hand side wasn't interpreted as a RegEx.

**Comment by jdkato** [comment]
You can do:

```yaml
extends: substitution
message: "Use '%s' instead of '%s'."
level: error
action:
  name: replace
swap:
  endusers?: end user|end users
```
Which will result in a `message` of 

> Use 'end user' or 'end users' instead of 'endusers'.
