### ISSUE TITLE
Make spelling filters customizable

### ISSUE THREAD

**Issue by jdkato** [vale-cli/vale#64]
- [x] Document default filters
- [x] support adding new filters and disabling default ones

**Comment by jdkato** [comment]
This has been merged into master. You can now disable the built-in filters and/or add your own:

```yaml
extends: spelling
message: "Did you really mean '%s'?"
level: error
# This disables the built-in filters. If you omit this key or set it to false,
# custom filters (see below) are added on top of the built-in ones.
#
# By default, Vale includes filters for acronyms, abbreviations, and numbers.
custom: true
# A "filter" is a regular expression specifying words to ignore during spell
# checking.
filters:
  - '[pP]y.*\b' # Ignore all words starting with 'py' -- e.g., 'PyYAML'.
ignore: ci/vocab.txt
```
If neither `custom` nor `filters` is defined, the functionality is equivalent to before (i.e., this shouldn't break existing `spelling` rules).
