### ISSUE TITLE
Multiple `raw` Tokens Break Rule

### ISSUE THREAD

**Issue by p0fi** [vale-cli/vale#645]
### Check for existing issues

- [X] Completed

### Environment

* OS: macOS
* Install method: Homebrew
* Vale version: `vale version 2.27.0`

### Describe the bug / provide steps to reproduce it

When creating a rule which uses the `raw` yaml key, more than one value for this key makes vale to ignore the rule entirely.

Example:
```yml
extends: existence
message: 'Don't use cols or width setting'
level: error
scope: raw
raw:
  - '\[[^\]]*cols=\"[^\"]*\"[^\]]*\]\s*\|==='
  - '\[[^\]]*width=\"[^\"]*\"[^\]]*\]\s*\|==='
```

This rule does not work. However if the second value under the `raw` key is removed it does work as expected.

**Comment by jdkato** [comment]
It appears that you'd like to match `\[[^\]]*cols=\"[^\"]*\"[^\]]*\]\s*\|===` *or* `\[[^\]]*width=\"[^\"]*\"[^\]]*\]\s*\|===`, which is not what this rule does. As [explained here](https://vale.sh/docs/topics/styles/#existence), when using `raw` (instead of `tokens`), the entries are concatenated.

I think something like

```yaml
extends: existence
message: "Don't use cols or width setting"
level: error
scope: raw
raw:
  - '(?:\[[^\]]*cols=\"[^\"]*\"[^\]]*\]\s*'
  - '|\[[^\]]*width=\"[^\"]*\"[^\]]*\]\s*)'
  - '\|==='
```

is closer to what you're trying to do.
