### ISSUE TITLE
Beginning/End of Line Does Not Work in Regex Patterns

### ISSUE THREAD

**Issue by p0fi** [vale-cli/vale#646]
### Check for existing issues

- [X] Completed

### Environment

* OS: macOS
* Install method: Homebrew
* Vale version: `vale version 2.27.0`

### Describe the bug / provide steps to reproduce it

When creating a rule the regex tokens for beginning (`^`) or end of line (`$`) are not working. When using them in a regex pattern the rule is ignored by vale

Example Rule:
```yaml
extends: existence
message: "End of line test"
level: error
scope: raw
raw: "123$"
```

This should point out `123` at the end of a line as an error but it does not work. Using `^123` to detect `123` at the start of a line does not work either.

I believe that this is also the underlying reason why the initial approach in #501 didn't work. While there is an acceptable solution to the end of a line with `\n` I don't know one for the start of a line.

**Comment by jdkato** [comment]
When using `raw`, you need to construct the entire pattern yourself. So, in this case, you need to add the `(?m)` modifier:

```yaml
extends: existence
message: "End of line test"
level: error
scope: raw
raw: '(?m)123$'
```

That said, my advice is to always use `tokens` unless you really know that you need more control:

```yaml
extends: existence
message: "End of line test"
level: error
scope: raw
tokens: 
  - '123$'
```
