### ISSUE TITLE
Rule that worked in 2.23 does not work in 2.27

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#657]
### Check for existing issues

- [X] Completed

### Environment

Tested on Linux/Mac, locally and in CI/CD pipelines.

Vale 2.23 and 2.27

### Describe the bug / provide steps to reproduce it

The following rule works fine in 2.23, but fails to find violations in 2.27. I only noticed because we updated our pipelines to 2.27, but I forgot to update Vale locally:

- https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/.vale/gitlab/CurlStringsQuoted.yml 

Some changes were merged into the `gitlab` project after we updated to 2.27, and when I ran vale locally with 2.23 the violations got picked up. So I'm not yet sure where the bug started, between 2.24 to 2.27. The rule is a `scope: code` rule, looking to make sure we double quote URLs in cURL examples.

You can see the two violations in this merge request (where I fixed them to use double quotes): https://gitlab.com/gitlab-org/gitlab/-/merge_requests/125495/diffs

**Comment by jdkato** [comment]
This was changed in [v2.26.0](https://github.com/errata-ai/vale/releases/tag/v2.26.0) (although it shouldn't have failed silently -- that has now been fixed).

Instead of using the inline scopes (`code`, `link`, `strong`, and `emphasis`) directly, the supported approach is to now use `scope: raw` and match against the relevant markup. 

For example, 

```yaml
# OLD
message: "'%s' left in text"
extends: existence
ignorecase: false
level: suggestion
scope: strong
tokens:
  - XXX
  - FIXME
  - TODO
  - NOTE
```

```yaml
# NEW
message: "'%s' left in text"
extends: existence
ignorecase: false
level: suggestion
nonword: true
scope: raw
tokens:
  - (?<=\*\*)(?:TODO|NOTE|FIXME|XXX)(?=\*\*)
```

I try to avoid making these pseudo-breaking changes to rules, but the performance improvements (memory-consumption wise) are significant.
