### ISSUE TITLE
"Node.js" should not be rejected

### ISSUE THREAD

**Issue by stevepiercy** [vale-cli/vale#666]
### Check for existing issues

- [X] Completed

### Describe the feature

I tried including the following in our `accept.txt`:

```
Node.js
Node.js®
Node\.js
```

All of them get rejected by Vale:

```console
 26:9     error       Avoid using 'js'.                                                           Vale.Avoid               
```

I suspect that Vale interprets the dot `.` in "Node.js" as a boundary character, and breaks it into two words, "Node" and "js".

Next I tried creating a [conditional style](https://vale.sh/docs/topics/styles/#conditional) that would look for "Node" immediately followed by "js", but it had no effect. I'm not sure how to write such a thing. Here it is.

```yml
extends: conditional
message: "'%s' should be spelled as Node.js."
level: error
scope: text
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\bNode\b'
second: '(?:\bjs\b)'
```

For now, I put it in markup as a Glossary term, and it passes:

```
{term}`Node.js`
```
