### ISSUE TITLE
[Vale Studio]: rule firing on content in backticks 

### ISSUE THREAD

**Issue by rohennes** [vale-cli/vale#673]
Why does this rule sometimes flag on code snippets in backticks? 

It seems that if there is no line break after the sentence with the backticks, it works unexpectedly. I am expecting the rule to never be triggered by content in backticks.

regex101: https://regex101.com/r/GB4Wzm/1

```yml
---
extends: substitution
ignorecase: false
level: error
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/reference-guide/casesensitiveterms/
message: Use '%s' rather than '%s'.
# source: "https://redhat-documentation.github.io/supplementary-style-guide/#glossary-terms-conventions"
action:
  name: replace
swap:
  linuxptp: test
```

## Text

```markdown
The linuxptp resource.

The `linuxptp` resource.
The linuxptp resource.


The linuxptp resource.

The `linuxptp` resource.

The linuxptp resource.
```

![image](https://github.com/errata-ai/vale/assets/104497497/546f5fcb-e096-4447-bb71-59324ceb4a04)
