### ISSUE TITLE
Error highlighting effected by surrounding lines

### ISSUE THREAD

**Issue by rohennes** [vale-cli/vale#674]
Hello, 

The highlighting of an incorrect term seems to be effected by adding line breaks, removing instances of the same error on a previous line etc. I am expecting only "using" to flag in the below example. 

This is simlar to #673 but not only limited to content in backticks. Thanks as always for your help and responsiveness!

https://regex101.com/r/8NYdwH/1    

```yml
---
extends: substitution
ignorecase: false
level: suggestion
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/termssuggestions/
message: "Depending on the context, consider using '%s' rather than '%s'."
action:
  name: replace
swap:
  "(?<!by) using": " by using| that uses"

```

## Text

```markdown
Start by using this.

Start by using this.
Start using this.

Start by using this.

Start by using this.

Start using this.
```
