### ISSUE TITLE
Headings starting with numbers do not qualify as sentence case.

### ISSUE THREAD

**Issue by loks0n** [vale-cli/vale#695]
### Check for existing issues

- [X] Completed

### Environment

OS: MacOS
Install method: Node wrapper package
Vale version: 2.29.1

### Describe the bug / provide steps to reproduce it

Headings starting with numbers, e.g. `# 1. My numbered heading` do not qualify as sentence case.

Reproduction steps

1. Create a rule in your style for sentence case headings:
```yaml
extends: capitalization
message: "'%s' should be in sentence case"
level: warning
scope: heading
match: $sentence
```

2. Create a number heading in a file 
```markdown
# 1. An important heading
Some text.

## An unimportant heading
Some text
```

3. Run vale with the rule from the style configured and observe the error.
```
1:5    warning  '1. An important heading'       mycustomstyle.SentenceCase 
                  should be in sentence case
```
