### ISSUE TITLE
Unwanted warnings raised with version 2.29.4

### ISSUE THREAD

**Issue by SMoraisAnsys** [vale-cli/vale#706]
### Check for existing issues

- [X] Completed

### Environment

I'm using value through the github action errata-ai/vale-action@reviewdog but I think it is appropriate to open an issue here as my problem arises when a change the vale version.

Here is my action setting:
```
  doc-style:
    name: "Check documentation style"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Running Vale
        uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: doc
          reporter: github-pr-check
          level: error
          filter_mode: nofilter
          fail_on_error: true
          vale_flags: "--config=doc/.vale.ini"
```

and my .vale.ini contains 

```
StylesPath = "styles"
MinAlertLevel = warning
IgnoredScopes = code, tt
SkippedScopes = script, style, pre, figure
WordTemplate = \b(?:%s)\b
Packages = Google
Vocab = perso # This accepts PEP 8 (cf my rst file context)

[*.{rst}]

BasedOnStyles = Vale, Google
TokenIgnores = (:.*:`.*`)

Google.WordList = NO
Google.Colons = NO
```

### Describe the bug / provide steps to reproduce it

The error I'm facing is that when vale works on my .rst file, the google rule regarding Heading is triggered when it shouldn't.

Here is my rst file

```
PEP 8
=====
blabla

Imports
-------
blabla

Import location
~~~~~~~~~~~~~~~
blabla
```

and the associated errors 

```
 {"message": "[Google.Headings] 'PEP 8' should use sentence-style capitalization.", ..., "severity": "WARNING"}
 {"message": "[Google.Headings] 'Imports' should use sentence-style capitalization.", ... , "severity": "WARNING"}
 {"message": "[Google.Headings] 'Import location' should use sentence-style capitalization.", ... , "severity": "WARNING"}
```

While I though that this error might be related to https://github.com/errata-ai/vale/discussions/702, using `Google.Headings = NO` didn't solve my issue. However, this warnings are no longer raised when I constraint the vale github action to use the version "2.29.3" (latest is "2.29.4").
