### ISSUE TITLE
Title case rules error out when everything is already capitalized

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#716]
### Check for existing issues

- [X] Completed

### Description

Rule:

```yaml
extends: capitalization
message: "'%s' should be in title case"
level: error
scope: heading.md
match: $title
style: AP # AP or Chicago; only applies when match is set to $title.
exceptions:
  - gRPC
```

Github Action:

```yaml
name: reviewdog
on: [pull_request]

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      ..........
      - name: reviewdog
        uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          separator: ","
          files: ${{ steps.files.outputs.added_modified }}
          reporter: github-check
          fail_on_error: true
```

I've not changed the configuration or github action for a few months and the rule was working as intended. These few days I've been noticing exceptions such as:

![image](https://github.com/errata-ai/vale/assets/39619599/cc3836de-d84e-46f0-a8a5-a6b5a8f7ee3c)

![image](https://github.com/errata-ai/vale/assets/39619599/929afa60-a2aa-4470-ada6-8714a10a920f)

As you can see they're already in title case and Vale should not report an error.

What could have changed recently? Appreciate any pointer.
