### ISSUE TITLE
Partial match or regex for capitalization exclusions

### ISSUE THREAD

**Issue by seancdavis** [vale-cli/vale#739]
### Check for existing issues

- [X] Completed

### Describe the feature

We have the following configuration for capitalization:

```yml
extends: capitalization
message: "Headings should be in sentence case."
level: warning
scope: heading
match: $sentence
```

In some cases, proper noun terms will be capitalized and break the sentence case rule.

I'd like to be able to add these terms to be excluded, regardless of the content surrounding them. Is there a way to achieve this today?
