### ISSUE TITLE
Parsing error of Hunspell dictionaries

### ISSUE THREAD

**Issue by karl-johan-grahn** [vale-cli/vale#740]
### Check for existing issues

- [X] Completed

### Environment

Similar to https://github.com/errata-ai/vale/issues/328, I'm attempting to use https://github.com/LibreOffice/dictionaries/tree/master/sv_SE with vale version 2.30.0 but get:
```
$ vale --config='path-to-config/.vale.ini' content
E201 Invalid value [config.yml:1:1]:

   1* extends: spelling
   2  message: "'%s' is a typo!"
   3  level: error

error parsing regexp: unexpected ): `^)(abiotisk|abnorm|...
```

I get other various parsing errors for other languages too, but I would need support for Swedish in particular right now. Thank you in advance for time to troubleshoot this, and let me know how I can help.

### Describe the bug / provide steps to reproduce it

1. Download https://github.com/LibreOffice/dictionaries/tree/master/sv_SE
2. Use latest vale
3. Extension:
    ```yml
    extends: spelling
    message: "'%s' is a typo!"
    level: error
    dicpath: <path-to-dictionary>/dictionaries/sv_SE
    dictionaries:
      - sv_SE
    ```
4. Run vale on any content, doesn't need to be Swedish because it fails prematurely at parsing the Hunspell dictionary: `vale --config='path-to-config/.vale.ini' content`
