### ISSUE TITLE
AP style title case rule for `to` is somewhat wrong

### ISSUE THREAD

**Issue by kayx23** [vale-cli/vale#742]
### Check for existing issues

- [X] Completed

### Description

My rule:

```yaml
extends: capitalization
message: "'%s' should be in title case"
level: error
scope: heading.md
match: $title
style: AP
exceptions:
  - none
```

It errors out on this title because of the `to`:

![image](https://github.com/errata-ai/vale/assets/39619599/cf9fd243-201c-4915-b3ba-cbc3673b1079)

Now, according to AP, `to` is not required to be capitalized when it is a preposition. Capitalization is required when `to` is part of an infinitive verb. Therefore I believe this is a bug, as the current rule would actually require `to` to be capitalized in all occurrences when API rule is in use.
