### ISSUE TITLE
Equals condition doens't work

### ISSUE THREAD

**Issue by ArthurFlag** [vale-cli/vale#763]
### Check for existing issues

- [X] Completed

### Environment

MacOS 14.2.1
vale version 3.0.5 via homebrew

### Describe the bug / provide steps to reproduce it

When using this style:

```yaml
extends: metric
message: "You cannot have only one H2."
level: error
formula: |
  heading.h2
condition: "<= 1"
```

Vale runs and reports errors correctly. 

When using:

```yaml
extends: metric
message: "You cannot have only one H2."
level: error
formula: |
  heading.h2
condition: "= 1"
```

I get:

```text
E201 Invalid value H2unique.yml:6:1]:

   5    heading.h2
   6* condition: "= 1"

script run: Parse Error: expected ')', found '='
	at (main):1:46

Execution stopped with code 1.
```

[Judging from the docs](https://vale.sh/docs/topics/styles/#metric), it should work, or am I misunderstanding something?

`== 1` doesn't seem to break or do anything.
