### ISSUE TITLE
Ruby format treats interpolated strings as comments.

### ISSUE THREAD

**Issue by reitermarkus** [vale-cli/vale#818]
### Check for existing issues

- [X] Completed

### Environment

Using the Ruby format, strings with interpolation are treated as comments.

macOS/Homebrew/3.4.1

### Describe the bug / provide steps to reproduce it

Running `vale` with the style rule 

```yaml
---
extends: existence
message: "'%s' should have one space."
link: "https://github.com/Homebrew/brew/blob/HEAD/docs/Prose-Style-Guidelines.md#typographical-conventions"
level: error
nonword: true
tokens:
  - "[a-z][.?!][A-Z]"
  - "[.?!] {2,}[A-Z]"
```

on a Ruby file containing

```ruby
"#{args.HEAD?}"
```

results in 

```
 1:7  error  's.H' should have one space.  Homebrew.Spacing 
```
