### ISSUE TITLE
Proposal: Capitalization support for spelling rule

### ISSUE THREAD

**Issue by Ravlen** [vale-cli/vale#871]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great if there was a way to flag words that were spelled correctly, but not capitalized correctly, with the current spelling style rule. I realize I could maintain two lists, one for spelling, and a separate one for capitalization, but that would be a maintenance burden when the correct spelling and capitalization is already in the spelling ignore list. Maintaining two lists would mean that every mis-capitalized word would be flagged as a problem twice.

Using `OpenID` as an example word that could be in the `ignore.txt` exceptions list, with a basic spelling rule:

```yaml
extends: spelling
message: "Did you really mean '%s'?"
level: error
ignore:
  - ignore.txt
```

If you use `Openid` (correct letters, incorrect capitalization), the error would be `Did you really mean 'Openid'?`. But the spelling is technically correct, it's just the capitalization that' s wrong. Since the exceptions list does contain the correct capitalization, I wonder if Vale could make use of that somehow? Perhaps:

```yaml
extends: spelling
message: "Is '%s' spelled correctly?"
capitalization_message: "'%s' is spelled correctly, but should be capitalized as '%s'."
level: error
ignore:
  - ignore.txt
```

That way, general spelling AND capitalization can all be handled by a single rule.
