### ISSUE TITLE
Substitution with "ignorecase: true" doesn't produce the expected result

### ISSUE THREAD

**Issue by alexvonme** [vale-cli/vale#873]
### Check for existing issues

- [X] Completed

### Environment

1. Linux
    - VS Code Extension
    - Direct Download
    - Version: 3.7.0

2. Vale Studio
    - Version: 3.6.1

### Describe the bug / provide steps to reproduce it

I wanted to create a rule that corrects miswritten versions for the abbreviation of Mozilla Public License (MPL):

```
extends: substitution
ignorecase: true
level: warning
message: Use '%s' instead of '%s'
action:
  name: replace
swap:
  MPL: MPL
  MPL[ -]?2(?:\.0)?: MPL 2.0
```

However, the rule doesn't correct "mpl 2.0" regardless of any changes I've made to it. The results are:

```
Matched
mpl
mpl 2
mpl2.0
MPL2.0

Not Matched
mpl 2.0

Correct
MPL
MPL 2.0
```

In case a relatively complex rule doesn't handle ``ignorecase: true`` well, I also tried to write more explicit rules but I still couldn't reach and change "mpl 2.0". The rule performs well with the other examples, could it be that with ``ignorecase: true``, complicated rule corrections are also taken with ignorecase?

Alternatively, is there a syntax issue in the rule that I'm missing?
