### ISSUE TITLE
Exceptions for Spacing rule not working

### ISSUE THREAD

**Issue by j-wol** [vale-cli/vale#894]
### Check for existing issues

- [X] Completed

### Environment

OS: Ubuntu Linux
Install method: direct download
Vale version: 3.3.0

### Describe the bug / provide steps to reproduce it

In my setup I make use of the following Spacing rule that warns when a dot is not followed by a space.
>extends: existence
>message: "'%s' should have one space."
>level: warning
>nonword: true

>tokens:
>    - '[a-z][.][A-Z]'

Unfortunately, this rule introduces some false positives when a mail address in the form "Firstname.Lastname@domain.com" is present in the documents.

My first idea to overcome that was to make use of the "exceptions" key of the existence style:
>exceptions:
>    - '\S+@\S+$'

Unfortunately, that has no impact and filters nothing. I searched a bit for such issues and found [this](https://github.com/errata-ai/vale/commit/4dfe2880fcf7ce4aadc8fcfd3cdddef5ca0bc58f) commit which (when I interpret it correctly) removed the usage of the "exceptions" key. In case my interpretation in correct, I would suggest to adopt the [documentation](https://vale.sh/docs/topics/styles/) accordingly. Otherwise, please let me know how to properly formulate exceptions.

My second try to filter out such mail addresses was to make use a [Vocabulary](https://vale.sh/docs/topics/vocab/). The newly introduced Vocabulary simply consists of a accept.txt with following entry:
>'\S+@\S+$'

This has no impact as well.
Then I tested a bit and put the regex in square brackets:
>[\S+@\S+$]

That now unfortunately, filter out all previous findings from the Spacing rule, even valid ones like "... end of last sentence.New sentence".

Could you please provide some hints, how to exclude mail addresses of the form "Firstname.Lastname@domain.com"?

**Comment by jdkato** [comment]
Your exceptions did not work because they never matched the search string: your rule (`[a-z][.][A-Z]`) is finding strings like "a.B" and comparing it to `'\S+@\S+$`, which is never going to match.

Here are two possible solutions:

1. Use a positive lookahead ([Vale Studio](https://studio.vale.sh/s/a031b220eea5ae29a89361492c8a01d4)):

   ```yaml
   extends: existence
   message: "'%s' should have one space."
   level: warning
   nonword: true
   tokens:
    - '[a-z][.][A-Z](?=[^@\n]+$)'
   ```
2. Use an appropriately-scoped exception ([Vale Studio](https://studio.vale.sh/s/628582e1d07450b73df0b9d1b820a08c)).

    ```yaml
    extends: existence
    message: "'%s' should have one space."
   level: warning
   nonword: true
   tokens:
     - '[a-z][.][A-Z][^\s]+'
   exceptions:
     - '\S+@\S+'
   ```
