### ISSUE TITLE
Allow for first use vs. subsequent use rules

### ISSUE THREAD

**Issue by jsspric** [vale-cli/vale#904]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be helpful to be able to flag the first use of an acronym and remind the user to define it on first use. 

For example:

> To access the system, you need a PIN. Enter your PIN at the prompt. 

I would like to be able to have it flag the first use of "PIN" and suggest replacing it with "personal identification number (PIN)", but ignore all subsequent uses.

**Comment by jdkato** [comment]
You can do this by defining a `limit` for the rule:

```yaml
extends: existence
message: "Make sure you define '%s'."
level: error
# only report once
limit: 1
tokens:
  - "PIN"
```
But this won't be able to tell if "PIN" has in fact been defined. In other words, you'll always see the alert.

The [`conditional`](https://vale.sh/docs/topics/styles/#conditional) extension point allows you to handle both cases.
