### ISSUE TITLE
Spell checking `ignore`

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#91]
I've never been very sure how to get the `ignore` parameter to work correctly, as it seems to look for the file relative to file you are checking, not the _.vale.ini_ file, or any yaml checks.

Ideally (and for portability among teams etc) I feel it should check for the file relative to the configuration files, or maybe using some sort of variable like `$VALE_CONFIG_PATH` etc. Does that make sense? Basically at the moment it seems I have to hard code the path to an ignore file, or keep all the ignore files in my project directories. Which makes sense to a point, but doesn't allow for easy config sharing.

**Comment by jdkato** [comment]
It's currently relative to the directory from which Vale is called. The inspiration for this was [GNU Aspell](http://aspell.net/), which was one of the few command-line spell checkers that supported an ignore file.

I can see, though, how this could be confusing within the context of Vale's more complex configuration (i.e., `.vale.ini`, `StylesPath`, etc.). 

The best solution is probably to make all of Vale's external, style-related resources relative to `StylesPath` (which is specified in the `.vale.ini` file). For example,

```yaml
extends: spelling
message: "Did you really mean '%s'?"
level: error
# We expect this to be $StylesPath/vocab.txt. If it's not found, fall back
# to the current method (for backwards compatibility).
ignore: vocab.txt
# We could also do something like `ignore: skip/vocab.txt`, which would be
# `$StylesPath/skip/vocab.txt`.
```
I'll try to incorporate a change along these lines in `v1.1.6` (as well as a re-write of https://errata-ai.github.io/vale/config/, which needs to be much more detailed).
