### ISSUE TITLE
Glob pattern excludes package

### ISSUE THREAD

**Issue by wkoot** [vale-cli/vale#923]
### Check for existing issues

- [X] Completed

### Environment

Github workflow:
```
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          fail_on_error: true
          filter_mode: nofilter
          vale_flags: "--glob='!styles *.md'"
```

Vale version latest default, with `.vale.ini`:
```
StylesPath = styles
MinAlertLevel = suggestion
Vocab = Base
Packages = proselint

[*.md]
BasedOnStyles = Vale, proselint
```

### Describe the bug / provide steps to reproduce it

The glob pattern seems to exclude the proselint package from vale entirely, instead of only omitting it from the linting selection:
```
Installed reviewdog from 'https://github.com/reviewdog/reviewdog/releases/download/v0.17.0/reviewdog_0.17.0_Linux_x86_64.tar.gz' into '/home/runner/reviewdog'.
/home/runner/vale --glob='!styles/ *.md' sync
E100 [loadStyles] Runtime error
style 'proselint' does not exist on StylesPath
Execution stopped with code 1.
```

I'm trying to exclude the styles folder entirely, since it's throwing errors unrelated to what I want to lint:
```
  {"message": "[Vale.Spelling] Did you really mean 'Suchow'?", "location": {"path": "styles/proselint/README.md", "range": {"start": {"line": 1, "column": 31}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'Redistributions'?", "location": {"path": "styles/proselint/README.md", "range": {"start": {"line": 6, "column": 4}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'Redistributions'?", "location": {"path": "styles/proselint/README.md", "range": {"start": {"line": 8, "column": 4}}}, "severity": "ERROR"}
```

**Comment by jdkato** [comment]
The pattern should be `!styles/**/*.md`. You can learn more about the [supported syntax here](https://vale.sh/docs/guides/glob).

**Comment by wkoot** [comment]
Hmm, but I do want to include _all_ `*.md` files in any of (sub)dirs in the repo. The suggested `!styles/**/*.md` wouldn't do that.
I just want to exclude the files which are in `/styles` (as it is the configured `StylesPath` in `.vale.ini`), because the `proselint` md files throw errors.
The docs regarding glob pattern are not very extensive, i.e. how can I combine multiple glob patterns?

**Comment by paddyroddy** [comment]
@wkoot I had the same issue and ended up fixing it like this.

I didn't pass any args to the action, i.e.

```yaml
jobs:
  lint-prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run Vale
        uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review
```

and I made sure that the `.github/styles/**` files weren't linted (I was getting rules triggering the `README.md` within `proselint`), by having an empty `BasedOnStyles =`

```ini
StylesPath = .github/styles

# https://github.com/errata-ai/packages
Packages = proselint

[formats]
qmd = md

[*.{md,qmd}]
BasedOnStyles = custom,\
                proselint,\
                Vale

# Disable
Vale.Spelling = NO

# `vale sync` in CI means the packages are then linted, so turn them off
[.github/styles/**]
BasedOnStyles =
```

can see in action here https://github.com/paddyroddy/talks
