### ISSUE TITLE
Message format enforces quotes which limits usability of message text.

### ISSUE THREAD

**Issue by moxiegirl** [vale-cli/vale#943]
### Check for existing issues

- [X] Completed

### Describe the feature

vale version 3.9.2

Existing rule is:

```
extends: substitution
message: "Use %s instead of '%s'."
level: warning
ignorecase: false
action:
  name: replace
swap:
  Some phrase: some-sub
``` 
  

Output message is:
 
```
 Use 'some-sub' instead of 'Some phrase'. 
```

The code has hard coded the `'` so if my rule `message` is this:

```
message: "Use |%s| instead of '%s'."
```

Vale outputs this for the warning:

```
Use |'some-sub'| instead of 'Some phrase'.  
```

The goal is this which conveys the actual tag a user should use and is available for cut-n-paste:

```
Use |some-sub| instead of 'Some phrase'.  
```

**Comment by jdkato** [comment]
This is only true in a specific case (`substitution` with the `replace` action) since "|" is used as a [special character](https://vale.sh/docs/checks/substitution#multiple-suggestions) to denote multiple options.

Here's how I would write it:

```yaml
extends: substitution
message: "Use '%s' instead of '%s'."
level: warning
ignorecase: false
action:
  name: replace
swap:
  Some phrase: '\|some-sub\|'
```

This will work correctly from the CLI and in editor integrations (the suggestion will be `|some-sub|`).

Another option is to use `existence` and hard-code the message:

```yaml
extends: existence
message: "Use |some-sub| instead of '%s'."
level: warning
ignorecase: false
action:
  name: replace
  params:
    - "|some-sub|"
tokens:
  - Some phrase
```
