### ISSUE TITLE
Can't add exception for "A/B" in an existence rule checking for "/" character

### ISSUE THREAD

**Issue by micaswyers-work** [vale-cli/vale#956]
### Check for existing issues

- [x] Completed

### Environment

* OS: MacOS 14.5
* Install method: Homebrew
* Vale version: 3.9.3

### Describe the bug / provide steps to reproduce it

We have an existence rule that flags slash characters (/), however, we want to create an exception for "A/B".  Even after adding various exceptions in the rule .yml file, vale is still flagging "A/B" in the sample text. We think this could be an interaction with the `/` because it is a special character in regex.

We were only able to get Vale to ignore "A/B" by adding a TokenIgnore to the vale.ini file: `TokenIgnores = ((?i)a\/b test)`, which seems too aggressive.

[Vale Studio showing issue](https://studio.vale.sh/s/4e48c430284e1380a4a44f022c3bb9b6)

Thank you!

**Comment by jdkato** [comment]
The issue is that you're only looking for the `/` character and then trying to use exceptions that need additional context.

Something like this will work:

```yaml
---
extends: existence
message: "Use 'or' Avoid slashes (/) except in code."
link: https://developers.google.com/style/slashes
level: warning
nonword: True
tokens:
  - '.+/.+'
exceptions:
  - 'A/B'
  - 'A\/B'
  - 'A.B'
  - 'A//B'
  - 'A(.*)B'
```
